--- 
services: 
  courseservice: 
    build: "."
    depends_on: 
      - db
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=sqlserver;Database=master;User Id=sa;Password=MyStrongPassw0rd!
    image: courseservice
    ports: 
      - "8443:8443"
      - "80:80"
  db: 
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: MyStrongPassw0rd!
      MSSQL_MEMORY_LIMIT_MB: 3072
    expose: 
      - 1433
    hostname: 'sqlserver'
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports: 
      - "11433:1433"
version: "3"
