--- 
services: 
  web: 
    build:  .
    depends_on: 
      - db
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=192.168.99.101,1433;Database=master;User Id=sa;Password=MyStrongPassw0rd!;Encrypt=False;TrustServerCertificate=True;
    image: courseservice
    ports: 
      - "443:443"
      - "80:80"
  db: 
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: MyStrongPassw0rd!
      MSSQL_MEMORY_LIMIT_MB: 3072
    expose: 
      - 1433
    hostname: 'sqlserver'
    image: microsoft/mssql-server-linux:2017-latest
    ports: 
      - "1433:1433"
    volumes:  
      - ./data/mssql:/var/opt/mssql3
version: "3"
